//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_combo
    {
        public string id { get; set; }
        public string combo_id { get; set; }
        public string do_an_chi_tiet_id { get; set; }
    
        public virtual combo combo { get; set; }
        public virtual do_an_chi_tiet do_an_chi_tiet { get; set; }
    }
}
