//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dinh_dang_phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dinh_dang_phim()
        {
            this.suat_chieu = new HashSet<suat_chieu>();
        }
    
        public string id { get; set; }
        public string ten { get; set; }
        public Nullable<int> phu_thu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suat_chieu> suat_chieu { get; set; }
    }
}
