//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class do_an_chi_tiet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public do_an_chi_tiet()
        {
            this.chi_tiet_combo = new HashSet<chi_tiet_combo>();
            this.hoa_don_chi_tiet = new HashSet<hoa_don_chi_tiet>();
        }
    
        public string id { get; set; }
        public Nullable<int> don_gia { get; set; }
        public Nullable<bool> dang_ban { get; set; }
        public string do_an_id { get; set; }
        public string kich_co_do_an_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_combo> chi_tiet_combo { get; set; }
        public virtual do_an do_an { get; set; }
        public virtual kich_co_do_an kich_co_do_an { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoa_don_chi_tiet> hoa_don_chi_tiet { get; set; }
    }
}
