//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class do_an
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public do_an()
        {
            this.do_an_chi_tiet = new HashSet<do_an_chi_tiet>();
        }
    
        public string id { get; set; }
        public string ten { get; set; }
        public Nullable<bool> dang_ban { get; set; }
        public string loai_do_an_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<do_an_chi_tiet> do_an_chi_tiet { get; set; }
        public virtual loai_do_an loai_do_an { get; set; }
    }
}
