//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoa_don_chi_tiet
    {
        public string id { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<int> tong_tien { get; set; }
        public string do_an_chi_tiet_id { get; set; }
        public Nullable<int> hoa_don_id { get; set; }
        public string combo_id { get; set; }
    
        public virtual combo combo { get; set; }
        public virtual do_an_chi_tiet do_an_chi_tiet { get; set; }
        public virtual hoa_don hoa_don { get; set; }
    }
}
