//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoa_don
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoa_don()
        {
            this.hoa_don_chi_tiet = new HashSet<hoa_don_chi_tiet>();
        }
    
        public int id { get; set; }
        public string ngay_ban { get; set; }
        public Nullable<int> nhan_vien_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoa_don_chi_tiet> hoa_don_chi_tiet { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
