//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phim()
        {
            this.suat_chieu = new HashSet<suat_chieu>();
        }
    
        public string id { get; set; }
        public string ten { get; set; }
        public Nullable<int> thoi_luong { get; set; }
        public Nullable<int> gioi_han_tuoi { get; set; }
        public Nullable<System.DateTime> ngay_cong_chieu { get; set; }
        public string ngon_ngu { get; set; }
        public string dien_vien { get; set; }
        public string quoc_gia { get; set; }
        public string nha_san_xuat { get; set; }
        public string tom_tat { get; set; }
        public string trang_thai { get; set; }
        public Nullable<bool> da_xoa { get; set; }
        public string loai_phim_id { get; set; }
    
        public virtual loai_phim loai_phim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suat_chieu> suat_chieu { get; set; }
    }
}
