//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBanVePhimEntities : DbContext
    {
        public QLBanVePhimEntities()
            : base("name=QLBanVePhimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<combo> combo { get; set; }
        public virtual DbSet<chi_tiet_combo> chi_tiet_combo { get; set; }
        public virtual DbSet<dinh_dang_phim> dinh_dang_phim { get; set; }
        public virtual DbSet<do_an> do_an { get; set; }
        public virtual DbSet<do_an_chi_tiet> do_an_chi_tiet { get; set; }
        public virtual DbSet<ghe_ngoi> ghe_ngoi { get; set; }
        public virtual DbSet<gia_ve> gia_ve { get; set; }
        public virtual DbSet<hoa_don> hoa_don { get; set; }
        public virtual DbSet<hoa_don_chi_tiet> hoa_don_chi_tiet { get; set; }
        public virtual DbSet<kich_co_do_an> kich_co_do_an { get; set; }
        public virtual DbSet<khach_hang> khach_hang { get; set; }
        public virtual DbSet<loai_do_an> loai_do_an { get; set; }
        public virtual DbSet<loai_ghe> loai_ghe { get; set; }
        public virtual DbSet<loai_phim> loai_phim { get; set; }
        public virtual DbSet<nguoi_dung> nguoi_dung { get; set; }
        public virtual DbSet<phim> phim { get; set; }
        public virtual DbSet<phong_chieu> phong_chieu { get; set; }
        public virtual DbSet<suat_chieu> suat_chieu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vai_tro> vai_tro { get; set; }
        public virtual DbSet<ve_ban> ve_ban { get; set; }
        public virtual DbSet<ve_dat> ve_dat { get; set; }
        public virtual DbSet<ve_dat_chi_tiet> ve_dat_chi_tiet { get; set; }
    }
}
