//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ve_ban
    {
        public string id { get; set; }
        public Nullable<System.DateTime> ngay_ban { get; set; }
        public Nullable<int> tong__tien { get; set; }
        public string suat_chieu_id { get; set; }
        public string gia_ve_id { get; set; }
        public string ghe_id { get; set; }
        public int nhan_vien_id { get; set; }
        public string trang_thai { get; set; }
    
        public virtual ghe_ngoi ghe_ngoi { get; set; }
        public virtual gia_ve gia_ve { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
        public virtual suat_chieu suat_chieu { get; set; }
        public virtual ve_dat_chi_tiet ve_dat_chi_tiet { get; set; }
    }
}
