//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ve_dat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ve_dat()
        {
            this.ve_dat_chi_tiet = new HashSet<ve_dat_chi_tiet>();
        }
    
        public string id { get; set; }
        public Nullable<int> khach_hang_id { get; set; }
        public Nullable<System.DateTime> ngay_dat { get; set; }
    
        public virtual khach_hang khach_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ve_dat_chi_tiet> ve_dat_chi_tiet { get; set; }
    }
}
