//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ve_dat_chi_tiet
    {
        public string id { get; set; }
        public string ve_dat_id { get; set; }
    
        public virtual ve_ban ve_ban { get; set; }
        public virtual ve_dat ve_dat { get; set; }
    }
}
